name = "Clp"
uuid = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
repo = "https://github.com/JuliaOpt/Clp.jl.git"
version = "0.7.2"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Clp_jll = "06985876-5285-5a41-9fcb-8948a742cc53"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
BinaryProvider = "0.5.9"
Clp_jll = "=1.17.6"
MathOptInterface = "0.9.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
